### PR TITLE
[Finishes

### PR DESCRIPTION
**Pull request by vmuthabuku**

### CODE REVIEW

**Comment by vmuthabuku** [comment]
screenshot from 2018-08-09 11-54-48

**Comment by Enockkenya** [comment]
clean UI great work

**Comment by Gidraf** [comment]
it,s great and clean, but may be you consider the white font colour to be something darker for readability to user not them to strain so much

**Comment by Tony-Ndichu** [comment]
Good job bro, I like the theme colors and the image is well suited. However, check your buttons as they have the same message: login and signin

**Pull request merged**
